/run/verbose 0
/run/initialize

/vis/open

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/zoom 1.4


/vis/geometry/set/visibility World 0 true

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon blue

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
